/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VslRouteImport } from './routes/vsl'
import { Route as OfertaEspecialRouteImport } from './routes/oferta-especial'
import { Route as IndexRouteImport } from './routes/index'

const VslRoute = VslRouteImport.update({
  id: '/vsl',
  path: '/vsl',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaEspecialRoute = OfertaEspecialRouteImport.update({
  id: '/oferta-especial',
  path: '/oferta-especial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oferta-especial': typeof OfertaEspecialRoute
  '/vsl': typeof VslRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oferta-especial': typeof OfertaEspecialRoute
  '/vsl': typeof VslRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oferta-especial': typeof OfertaEspecialRoute
  '/vsl': typeof VslRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/oferta-especial' | '/vsl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/oferta-especial' | '/vsl'
  id: '__root__' | '/' | '/oferta-especial' | '/vsl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OfertaEspecialRoute: typeof OfertaEspecialRoute
  VslRoute: typeof VslRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vsl': {
      id: '/vsl'
      path: '/vsl'
      fullPath: '/vsl'
      preLoaderRoute: typeof VslRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta-especial': {
      id: '/oferta-especial'
      path: '/oferta-especial'
      fullPath: '/oferta-especial'
      preLoaderRoute: typeof OfertaEspecialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OfertaEspecialRoute: OfertaEspecialRoute,
  VslRoute: VslRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
